# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy server script
COPY solo_server.py /app/solo_server.py

# Install Python dependencies
RUN pip install --no-cache-dir mcp pandas pymysql

# Set entrypoint
ENTRYPOINT ["python", "solo_server.py"]
